flask_blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField(
        'Заголовок',
        validators=[DataRequired()]
    )
    content = TextAreaField(
        'Содержимое',
        validators=[DataRequired()]
    )
    submit = SubmitField('Отправить')

flask_blog/main/routes.py
from flask import render_template, Blueprint
from flask_blog.models import User

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/home')
def home():
    return render_template('index.html')


@main.route('/contacts')
def contacts():
    return render_template('contact.html')

flask_blog/posts/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required

from flask_blog import db
from flask_blog.models import Post
from flask_blog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route('/allpost')
@login_required
def allpost():
    page = request.args.get('page', 1, type=int)
    post_list = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('allpost.html', posts=post_list)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Ваш пост создан!', 'success')
        return redirect(url_for('posts.allpost'))
    return render_template('create_post.html', title='Новая статья', form=form, legend='Новая статья')


@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Ваш пост обновлён!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Обновление статьи', form=form, legend='Обновление статьи')


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Ваш пост был удалён!', 'success')
    return redirect(url_for('posts.allpost'))

flask_blog/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required

from flask_blog import db, bcrypt
from flask_blog.models import User, Post
from flask_blog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flask_blog.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Ваша учётная запись была создана! Теперь вы можете войти в систему', 'success')
        return redirect(url_for('users.login'))  # return redirect(url_for('main.home'))
    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)

            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('posts.allpost'))
        else:
            flash('Войти не удалось. Пожалуйста, проверьте электронную почту и пароль', 'внимание')
    return render_template('login.html', title='Аутентификация', form=form)


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()

    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Ваш аккаунт был обновлён!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        page = request.args.get('page', 1, type=int)
        user = User.query.filter_by(username=form.username.data).first_or_404()
        posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    image_file = url_for('static', filename='profile_pics' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form, posts=posts, user=user)


@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route('/user/<string:username>')
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('На почту отправлено письмо с инструкциями по сбросу пароля.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Сброс пароля', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Это недействительный или просроченный токен', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Ваш пароль был обновлён! Теперь вы можете авторизоваться', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Сброс пароля', form=form)

flask_blog/templates/account.html
{% extends "base.html" %}

{% block content %}
<div id="main_content">
    <img style="border-radius: 50%;" class="avatar-big"
         src="{{ url_for('static', filename='profile_pics/' + current_user.image_file) }}">
    <h2>{{ current_user.username }} ({{ current_user.email }})</h2>

    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <h1>Аккаунт пользователя</h1>
        <div class="form_settings">
            <p>
                <span>{{ form.username.label }}</span>
                {% if form.username.errors %}
                {{ form.username }}
            <div class="invalid-feedback">
                {% for error in form.username.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.username }}
            {% endif %}
            </p>
            <p>
                <span>{{ form.email.label }}</span>
                {% if form.email.errors %}
                {{ form.email }}
            <div class="invalid-feedback">
                {% for error in form.email.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{ form.email }}
            {% endif %}
            </p>
            <p>
                <span>{{ form.picture.label }}</span>
                {{ form.picture }}
                {% if form.picture.errors %}
            <div class="invalid-feedback">
                {% for error in form.picture.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
            </p>
            <p style="padding-top: 15px"><span>&nbsp;</span>{{ form.submit(class="submit") }}</p>
        </div>
    </form>
</div>
{% endblock content %}

flask_blog/templates/allpost.html
{% extends "base.html" %}

{% block content %}
<div id="main_content">
    {% for post in posts.items %}
    <article style="display: flex; flex-direction: column;">
        <img style="margin-right: 5px;" class="avatar"
             src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <a href="{{ url_for('users.user_posts', username=post.author.username) }}" id="author">
            {{ post.author.username }}</a>

        <div class="card">
            <h2>
                <a href="{{ url_for('posts.post', post_id=post.id) }}">
                    {{ post.title}}
                </a>
            </h2>
            <p><small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small></p>
            <p>{{ post.content }}</p>
        </div>
    </article>
    {% endfor %}

    {% if posts.pages > 1 %}
        <div class="pagination" style="margin-bottom: 20px;">
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    {{ page_num }}
                {% else %}
                    <a href="{{ url_for('posts.allpost', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
        </div>
    {% endif %}

</div>
{% endblock content %}

flask_blog/templates/base.html
<!DOCTYPE HTML>
<html lang="ru">

<head>
    <title>Блог на Flask</title>
    <meta name="description" content="Учебный блог на Flask">
    <meta name="keywords" content="Flask, блог, бобёр">
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style/style.css') }}">
</head>

<body>
<div id="main">
    <div id="header">
        <div id="logo">
            <div id="logo_text">
                <h1><a href="{{ url_for('main.home') }}">Flask<span class="logo_colour">учебный блог</span></a></h1>
                <h2>Шаблог позаимствован и используется без комерческих целей</h2>
            </div>
        </div>
        <div id="menubar">
            <ul id="menu">
                {% if current_user.is_authenticated %}
                    <li {% if request.endpoint=="posts.allpost" %} class="selected" {% endif %}>
                        <a href="{{ url_for('posts.allpost') }}">
                            <i class="fa fa-file"></i> Статьи</a></li>
                    <li {% if request.endpoint=="users.user_posts" %} class="selected" {% endif %}>
                        <a href="{{ url_for('users.user_posts', username=current_user.username) }}">
                            <i class="fa fa-folder"></i> Статьи {{ current_user.username }}</a></li>
                    <li {% if request.endpoint=="posts.new_post" %} class="selected" {% endif %}>
                        <a href="{{ url_for('posts.new_post') }}">
                            <i class="fa fa-plus"></i> Создать статью</a></li>
                    <li {% if request.endpoint=="users.account" %} class="selected" {% endif %}>
                        <a href="{{ url_for('users.account') }}">
                            <i class="fa fa-user"></i> Профиль</a></li>
                    <li {% if request.endpoint=="users.logout" %} class="selected" {% endif %}>
                        <a href="{{ url_for('users.logout') }}">
                            <i class="fa fa-sign-out"></i> Выйти</a></li>
                {% else %}
                    <li {% if request.endpoint=="users.login" %} class="selected" {% endif %}>
                        <a href="{{ url_for('users.login') }}">
                            <i class="fa fa-sign-in"></i> Войти</a></li>
                    <li {% if request.endpoint=="users.register" %} class="selected" {% endif %}>
                        ><a href="{{ url_for('users.register') }}">
                        <i class="fa fa-user-plus"></i> Зарегистрироваться</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    <div id="content_header"></div>
    <div id="site_content">
        <div id="banner"></div>
        <div id="sidebar_container">
            <div class="sidebar">
                <div class="sidebar_top"></div>
                <div class="sidebar_item">
                    <h3>Последние новости</h3>
                    <h4>Бложек запущен</h4>
                    <h5>18 августа 2022</h5>
                    <p>Мы строили, строили и наконец построили в 2022.<br><a
                            href="#">Читать далее</a></p>
                </div>
                <div class="sidebar_base"></div>
            </div>
            <div class="sidebar">
                <div class="sidebar_top"></div>
                <div class="sidebar_item">
                    <h3>Полезные ссылки (возможно когда-то появятся)</h3>
                    <ul>
                        <li><a href="#">Ссылка 1</a></li>
                        <li><a href="#">Ссылка 2</a></li>
                        <li><a href="#">Ссылка 3</a></li>
                        <li><a href="#">Ссылка 4</a></li>
                    </ul>
                </div>
                <div class="sidebar_base"></div>
            </div>
        </div>
        {% block content %}
        Здесь могла бы быть ваша реклама, но не будет ;-)
        {% endblock %}
    </div>
    <div id="content_footer"></div>
    <div id="footer">
        <p><a href="{{ url_for('main.home') }}">Главная</a> | <a href="{{ url_for('main.contacts') }}">Контакты</a></p>
        <p>Copyright &copy; Bober Inc.</p>
    </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

</body>
</html>

flask_blog/templates/contact.html
{% extends "base.html" %}

{% block content %}
<div id="main_content">
    <h1>Контакты</h1>
    <p>Вы&nbsp;можете воспользоваться формой ниже, чтобы у&nbsp;вас появилось ощущение, что&nbsp;вы&nbsp;нам пишите, но&nbsp;она
        не&nbsp;работает:</p>
    <div class="form_settings">
        <p><span>Имя</span><input class="contact" type="text" name="name" value=""></p>
        <p><span>Email</span><input class="contact" type="text" name="email" value=""></p>
        <p><span>Сообщение</span><textarea class="contact textarea" rows="8" cols="50" name="enquiry"></textarea></p>
        <p style="padding-top: 15px"><span>&nbsp;</span>
            <input class="submit" type="submit" name="contact_submitted" value="Отправить"></p>
    </div>
    <p><br><br>Пожалуйста введите корректный e-mail.</p>
</div>
{% endblock content %}

flask_blog/templates/create_post.html
{% extends "base.html" %}

{% block content %}
<div id="main_content">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <h1>{{ legend }}</h1>
        <div class="form_settings">
            <p>
                <span>{{ form.title.label }}</span>
                {% if form.title.errors %}
                {{ form.title }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title }}
                {% endif %}
            </p>
            <p>
                <span>{{ form.content.label }}</span>
                {% if form.content.errors %}
                {{ form.content }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content }}
                {% endif %}
            </p>
            <p style="padding-top: 15px"><span>&nbsp;</span>{{ form.submit(class="submit") }}</p>
        </div>
    </form>
</div>
{% endblock content %}

flask_blog/templates/index.html
{% extends "base.html" %}

{% block content %}
<div id="main_content">
    <h1>Добро пожаловать учебный блог на&nbsp;Flask.</h1>
    <p>Здесь был другой текст но&nbsp;после исправления кодировок я&nbsp;его потерял, так что теперь, здесь это.</p>
    <p>В&nbsp;этом месте тоже был текст, который безвозвратно утрачен, всегда внимательно следите за&nbsp;кодировками файла!</p>
    <p>Тут я&nbsp;писал, что&nbsp;устал выдумывать текст, поэтому перехожу на&nbsp;lorem.</p>
    <h2>Lorem ipsum dolor</h2>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci, voluptas:</p>
    <ul>
        <li>Lorem ipsum dolor&nbsp;1</li>
        <li>Lorem ipsum dolor&nbsp;2</li>
        <li>Lorem ipsum dolor&nbsp;3</li>
    </ul>
</div>
{% endblock content %}

flask_blog/templates/login.html
{% extends "base.html" %}

{% block content %}
<div id="main_content">
    <h2>Авторизация</h2>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <div class="form_settings">
            <p>
                <span>{{ form.email.label }}</span>
                {% if form.email.errors %}
                {{ form.email }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email }}
                {% endif %}
            </p>
            <p>
                <span>{{ form.password.label }}</span>
                {% if form.password.errors %}
                    {{ form.password }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="form-control form-control-lg") }}
                {% endif %}
            </p>
            <p>
                <span>{{ form.remember.label }}</span>
                {{ form.remember(class="checkbox") }}
            </p>

            <p style="padding-top: 15px"><span>&nbsp;</span>
                {{ form.submit(class="submit") }}
                <a href="{{ url_for('users.reset_request') }}" style="margin-left: 10px;">Забыли пароль?</a>
            </p>
        </div>
    </form>
</div>
{% endblock content %}

flask_blog/templates/post.html
{% extends "base.html" %}

{% block content %}
<div id="main_content">
    <article style="display: flex; flex-direction: column;">
        <img style="margin-right: 5px;" class="avatar"
             src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <a href="{{ url_for('users.user_posts', username=post.author.username) }}" id="author">
            {{ post.author.username }}</a>

        <h1>{{ post.title }}</h1>
        <p><small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small></p>
        <p class="card-text">{{ post.content }}</p>
        {% if post.author == current_user %}
            <div class="card-footer">
                <a href="{{ url_for('posts.update_post', post_id=post.id) }}" class="button">Обновить</a>
                <button type="button" data-toggle="modal" data-target="#deleteModal" class="button del">Удалить</button>
            </div>
        {% endif %}
    </article>
</div>

<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h2 class="modal-title" id="deleteModalLabel">Удалить пост?</h2>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                    <input class="btn btn-danger" type="submit" value="Удалить">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

flask_blog/templates/register.html
{% extends "base.html" %}

{% block content %}
<div id="main_content">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <h2>Регистрация</h2>
        <div class="form_settings">
            <p>
                <span>{{ form.username.label }}</span>
                {% if form.username.errors %}
                    {{ form.username }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username }}
                {% endif %}
            </p>
            <p>
                <span>{{ form.email.label }}</span>
                {% if form.email.errors %}
                    {{ form.email }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email }}
                {% endif %}
            </p>
            <p>
                <span>{{ form.password.label }}</span>
                {% if form.password.errors %}
                    {{ form.password }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password }}
                {% endif %}
            </p>
            <p>
                <span>{{ form.confirm_password.label }}</span>
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_password }}
                {% endif %}
            </p>
            <p style="padding-top: 15px"><span>&nbsp;</span>{{ form.submit(class="submit") }}</p>
        </div>
    </form>
</div>
{% endblock content %}

flask_blog/templates/reset_request.html
{% extends "base.html" %}

{% block content %}
<div id="main_content">
    <h2>Сброс пароля</h2>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <div class="form_settings">
            <p>
                <span>{{ form.email.label }}</span>
                {% if form.email.errors %}
                {{ form.email }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email }}
                {% endif %}
            </p>
            <p style="padding-top: 15px"><span>&nbsp;</span>
                {{ form.submit(class="submit") }}</p>
        </div>
    </form>
</div>
{% endblock content %}

flask_blog/templates/reset_token.html
{% extends "base.html" %}

{% block content %}
<div id="main_content">
    <h2>Сброс пароля</h2>
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <div class="form_settings">
            <p>
                <span>{{ form.password.label }}</span>
                {% if form.password.errors %}
                {{ form.password }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password }}
                {% endif %}
            </p>
            <p>
                <span>{{ form.confirm_password.label }}</span>
                {% if form.confirm_password.errors %}
                {{ form.confirm_password }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                        <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_password }}
                {% endif %}
            </p>
            <p style="padding-top: 15px"><span>&nbsp;</span>
                {{ form.submit(class="submit") }}</p>
        </div>
    </form>
</div>
{% endblock content %}

flask_blog/templates/user_posts.html
{% extends "base.html" %}

{% block content %}
<div id="main_content">
    <h1 class="mb-3">Посты опубликованы пользователем {{ user.username }} ({{ posts.total }})</h1>
    {% for post in posts.items %}
    <article style="display: flex; flex-direction: column;">
        <img style="margin-right: 5px;" class="avatar"
             src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
        <a href="{{ url_for('users.user_posts', username=post.author.username) }}">
            {{ post.author.username }}</a>

        <div class="card">
            <h2>
                <a href="{{ url_for('posts.post', post_id=post.id) }}">
                    {{ post.title }}
                </a>
            </h2>
            <p><small>Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small></p>
            <p>{{ post.content }}</p>
        </div>
    </article>
    {% endfor %}

    {% if posts.pages > 1 %}
        <div class="pagination" style="margin-bottom: 20px;">
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    {{ page_num }}
                {% else %}
                    <a href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">
                        {{ page_num }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
        </div>
    {% endif %}

</div>
{% endblock content %}